# Кеш
proxy_cache_path /tmp/nginx_cache
    levels=1:2
    keys_zone=my_cache:10m
    max_size=100m
    inactive=60m
    use_temp_path=off;

# Load Balancer
upstream backend {
    server app1:80 weight=3;
    server app2:80 weight=1;
}

server {
    listen 8080;

    # Load Balancer
    location / {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # app1 з кешем
    location /app1/ {
        proxy_pass http://app1:80/;
        proxy_cache my_cache;
        proxy_cache_valid 200 1m;
        proxy_cache_use_stale error timeout;
        add_header X-Cache-Status $upstream_cache_status;
        proxy_set_header Host $host;
    }

    # app2 без кешу
    location /app2/ {
        proxy_pass http://app2:80/;
        proxy_set_header Host $host;
    }

    # Статус nginx
    location /status {
        stub_status on;
        allow all;
    }
}
